# -*- coding: utf-8 -*-
"""하천수의_수질현황_금강권역.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzVJowKeUyBQB-ycl7yiVY_GbftRXW28
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 폰트 설치"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] =False

"""## 2022년_하천수의_수질현황_금강권역"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/재정데이터_미니프로젝트_2조/하천수의+수질현황-금강권역_2022년.csv'
, header=[0,1],encoding='cp949')

df.head()

df.columns

# 상위 컬럼명 확인
print(df.columns[:10])
# 데이터 일부 확인
print(df.head())

import pandas as pd

# 원하는 키워드
keywords = ['총질소T-N', '총인T-P', '클로로필-a']

# 멀티인덱스 컬럼에서 1번 인덱스('총질소T-N' 등 항목명) 기준으로 필터링
selected_cols = [col for col in df.columns if any(k in col[1] for k in keywords)]

# 선택한 컬럼으로 새로운 데이터프레임 생성
df_selected = df[selected_cols]

print(df_selected.head())

import pandas as pd

# df : 현재 멀티인덱스 컬럼을 가진 원본 데이터프레임

# 1) 월별 필요한 컬럼(총질소, 총인, 클로로필)만 선택
# 2) 각 월별 데이터를 따로 뽑아서 합침

# 1) '분류' 컬럼(멀티인덱스 4단계 중 첫 4개가 '분류' 관련인 경우가 많으므로, 분류 컬럼 지정)
# 분류 컬럼은 멀티인덱스의 ('No','분류','분류','분류.1') 등으로 구성되어 있을 수 있으므로
# 정확히 어떤 컬럼이 분류인지 확인 후, 예시로 아래와 같이 분류명 컬럼 추출

classification_cols = [col for col in df.columns if '분류' in col[1]]  # 필요시 조정

# 2) 월 리스트
months = [f'2022년 {m}월' for m in range(1,13)]

# 3) 월별 데이터를 담을 리스트
dfs = []

for month in months:
    # 월별 3개 변수 컬럼만 추출 (총질소T-N, 총인T-P, 클로로필-a Chlorophyll-a)
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    # 분류 컬럼과 월별 데이터만 추출
    temp = df[classification_cols + month_cols].copy()

    # 컬럼 이름 단순화 (멀티인덱스 -> 단일 컬럼명)
    # ex: ('2024년 1월', '총질소T-N', 'mg/L', '원자료') -> '총질소T-N'
    temp.columns = [col[1] if '분류' in col[1] else col[1] for col in temp.columns]

    # 월 정보 컬럼 추가
    temp['월'] = month

    dfs.append(temp)

# 4) 월별 데이터 합치기
df_long = pd.concat(dfs, ignore_index=True)

# 5) 컬럼 순서 정리 (분류 컬럼 + 월 + 3개 변수)
cols_order = [col for col in classification_cols]
cols_order = [col[1] for col in classification_cols] + ['월', '총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']

df_long = df_long[cols_order]

print(df_long.head())

# 예를 들어, 중복된 분류 컬럼 9개가 반복되어 있다면,
# 분류 관련 컬럼을 중복 없이 하나만 남기도록 선택

# 1) 분류 컬럼명 리스트 (중복된 것 중 첫 3개만 선택)
classification_cols = [col for col in df.columns if '분류' in col[1]]

# 중복이 있을 수 있으므로, 컬럼명을 기준으로 중복 제거
seen = set()
unique_classification_cols = []
for col in classification_cols:
    if col[1] not in seen:
        unique_classification_cols.append(col)
        seen.add(col[1])

# 2) 위에서 월별 데이터 컬럼과 분류 컬럼 조합 예시
months = [f'2022년 {m}월' for m in range(1, 13)]

dfs = []

for month in months:
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    temp = df[unique_classification_cols + month_cols].copy()

    # 컬럼명 단순화
    temp.columns = [col[1] for col in unique_classification_cols] + [col[1] for col in month_cols]

    temp['월'] = month

    dfs.append(temp)

df_long = pd.concat(dfs, ignore_index=True)

print(df_long.head())

# 1. df_tp 복사본 생성 (원본에 영향 안주게)
df_tp = df_long[['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a', '월']].copy()

# 숫자형 변환 (변환 불가시 NaN 처리)
df_tp['총인T-P'] = pd.to_numeric(df_tp['총인T-P'], errors='coerce')
df_tp['총질소T-N'] = pd.to_numeric(df_tp['총질소T-N'], errors='coerce')
df_tp['클로로필-a Chlorophyll-a'] = pd.to_numeric(df_tp['클로로필-a Chlorophyll-a'], errors='coerce')

#2022금강권역_총인-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tp = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_bound = df_tp['총인T-P'].quantile(0.01)
upper_bound = df_tp['총인T-P'].quantile(0.99)

# 이상치 제거
df_tp_filtered = df_tp[(df_tp['총인T-P'] >= lower_bound) & (df_tp['총인T-P'] <= upper_bound)]

# 시각화 (월별로 나눠서 회귀선 포함)
sns.lmplot(
    data=df_tp_filtered,
    x='총인T-P',
    y='클로로필-a Chlorophyll-a',
    col='월',           # 월별 분할
    col_wrap=4,         # 한 줄에 4개씩 출력
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'blue'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총인(T-P) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2022금강권역_총질소-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tn = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_tn = df_tn['총질소T-N'].quantile(0.01)
upper_tn = df_tn['총질소T-N'].quantile(0.99)

# 이상치 제거
df_tn_filtered = df_tn[(df_tn['총질소T-N'] >= lower_tn) & (df_tn['총질소T-N'] <= upper_tn)]

# 시각화
sns.lmplot(
    data=df_tn_filtered,
    x='총질소T-N',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'red'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총질소(T-N) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2022금강권역_총영양염류-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거 및 총영양염류 계산
df_nut = df_tp.dropna()
df_nut['총영양염류'] = df_nut['총질소T-N'] + df_nut['총인T-P']

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_nut = df_nut['총영양염류'].quantile(0.01)
upper_nut = df_nut['총영양염류'].quantile(0.99)

# 이상치 제거
df_nut_filtered = df_nut[(df_nut['총영양염류'] >= lower_nut) & (df_nut['총영양염류'] <= upper_nut)]

# 시각화
sns.lmplot(
    data=df_nut_filtered,
    x='총영양염류',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'green'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총영양염류 vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

"""## 2023년_하천수의_수질현황_금강권역"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/재정데이터_미니프로젝트_2조/하천수의+수질현황-금강권역_2023년.csv'
, header=[0,1],encoding='cp949')

df.head()

df.columns

# 상위 컬럼명 확인
print(df.columns[:10])
# 데이터 일부 확인
print(df.head())

import pandas as pd

# 예: df는 이미 위와 같은 MultiIndex 컬럼을 가진 데이터프레임
# df = pd.read_excel(..., header=[0,1,2,3])

# 원하는 키워드
keywords = ['총질소T-N', '총인T-P', '클로로필-a']

# MultiIndex 컬럼에서 4번째 level까지 있으므로,
# 각 컬럼 튜플에서 1번 인덱스(두번째 레벨, 즉 '총질소T-N' 등 항목명) 기준으로 필터링
selected_cols = [col for col in df.columns if any(k in col[1] for k in keywords)]

# 선택한 컬럼으로 새로운 데이터프레임 생성
df_selected = df[selected_cols]

print(df_selected.head())

import pandas as pd

# df : 현재 멀티인덱스 컬럼을 가진 원본 데이터프레임

# 1) 월별 필요한 컬럼(총질소, 총인, 클로로필)만 선택
# 2) 각 월별 데이터를 따로 뽑아서 합침

# 1) '분류' 컬럼(멀티인덱스 4단계 중 첫 4개가 '분류' 관련인 경우가 많으므로, 분류 컬럼 지정)
# 분류 컬럼은 멀티인덱스의 ('No','분류','분류','분류.1') 등으로 구성되어 있을 수 있으므로
# 정확히 어떤 컬럼이 분류인지 확인 후, 예시로 아래와 같이 분류명 컬럼 추출

classification_cols = [col for col in df.columns if '분류' in col[1]]  # 필요시 조정

# 2) 월 리스트
months = [f'2023년 {m}월' for m in range(1,13)]

# 3) 월별 데이터를 담을 리스트
dfs = []

for month in months:
    # 월별 3개 변수 컬럼만 추출 (총질소T-N, 총인T-P, 클로로필-a Chlorophyll-a)
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    # 분류 컬럼과 월별 데이터만 추출
    temp = df[classification_cols + month_cols].copy()

    # 컬럼 이름 단순화 (멀티인덱스 -> 단일 컬럼명)
    # ex: ('2024년 1월', '총질소T-N', 'mg/L', '원자료') -> '총질소T-N'
    temp.columns = [col[1] if '분류' in col[1] else col[1] for col in temp.columns]

    # 월 정보 컬럼 추가
    temp['월'] = month

    dfs.append(temp)

# 4) 월별 데이터 합치기
df_long = pd.concat(dfs, ignore_index=True)

# 5) 컬럼 순서 정리 (분류 컬럼 + 월 + 3개 변수)
cols_order = [col for col in classification_cols]
cols_order = [col[1] for col in classification_cols] + ['월', '총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']

df_long = df_long[cols_order]

print(df_long.head())

# 예를 들어, 중복된 분류 컬럼 9개가 반복되어 있다면,
# 분류 관련 컬럼을 중복 없이 하나만 남기도록 선택

# 1) 분류 컬럼명 리스트 (중복된 것 중 첫 3개만 선택)
classification_cols = [col for col in df.columns if '분류' in col[1]]

# 중복이 있을 수 있으므로, 컬럼명을 기준으로 중복 제거
seen = set()
unique_classification_cols = []
for col in classification_cols:
    if col[1] not in seen:
        unique_classification_cols.append(col)
        seen.add(col[1])

# 2) 위에서 월별 데이터 컬럼과 분류 컬럼 조합 예시
months = [f'2023년 {m}월' for m in range(1, 13)]

dfs = []

for month in months:
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    temp = df[unique_classification_cols + month_cols].copy()

    # 컬럼명 단순화
    temp.columns = [col[1] for col in unique_classification_cols] + [col[1] for col in month_cols]

    temp['월'] = month

    dfs.append(temp)

df_long = pd.concat(dfs, ignore_index=True)

print(df_long.head())

# 1. df_tp 복사본 생성 (원본에 영향 안주게)
df_tp = df_long[['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a', '월']].copy()

# 숫자형 변환 (변환 불가시 NaN 처리)
df_tp['총인T-P'] = pd.to_numeric(df_tp['총인T-P'], errors='coerce')
df_tp['총질소T-N'] = pd.to_numeric(df_tp['총질소T-N'], errors='coerce')
df_tp['클로로필-a Chlorophyll-a'] = pd.to_numeric(df_tp['클로로필-a Chlorophyll-a'], errors='coerce')

#2023금강권역_총인-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tp = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_bound = df_tp['총인T-P'].quantile(0.01)
upper_bound = df_tp['총인T-P'].quantile(0.99)

# 이상치 제거
df_tp_filtered = df_tp[(df_tp['총인T-P'] >= lower_bound) & (df_tp['총인T-P'] <= upper_bound)]

# 시각화 (월별로 나눠서 회귀선 포함)
sns.lmplot(
    data=df_tp_filtered,
    x='총인T-P',
    y='클로로필-a Chlorophyll-a',
    col='월',           # 월별 분할
    col_wrap=4,         # 한 줄에 4개씩 출력
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'blue'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총인(T-P) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2023금강권역_총질소-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tn = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_tn = df_tn['총질소T-N'].quantile(0.01)
upper_tn = df_tn['총질소T-N'].quantile(0.99)

# 이상치 제거
df_tn_filtered = df_tn[(df_tn['총질소T-N'] >= lower_tn) & (df_tn['총질소T-N'] <= upper_tn)]

# 시각화
sns.lmplot(
    data=df_tn_filtered,
    x='총질소T-N',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'red'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총질소(T-N) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2023금강권역_총영양염류-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거 및 총영양염류 계산
df_nut = df_tp.dropna()
df_nut['총영양염류'] = df_nut['총질소T-N'] + df_nut['총인T-P']

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_nut = df_nut['총영양염류'].quantile(0.01)
upper_nut = df_nut['총영양염류'].quantile(0.99)

# 이상치 제거
df_nut_filtered = df_nut[(df_nut['총영양염류'] >= lower_nut) & (df_nut['총영양염류'] <= upper_nut)]

# 시각화
sns.lmplot(
    data=df_nut_filtered,
    x='총영양염류',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'green'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총영양염류 vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

"""## 2024년_하천수의_수질현황_금강권역"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/재정데이터_미니프로젝트_2조/하천수의+수질현황-금강권역_2024년.csv'
, header=[0,1],encoding='cp949')

df.head()

df.columns

# 상위 컬럼명 확인
print(df.columns[:10])
# 데이터 일부 확인
print(df.head())

import pandas as pd

# 예: df는 이미 위와 같은 MultiIndex 컬럼을 가진 데이터프레임
# df = pd.read_excel(..., header=[0,1,2,3])

# 원하는 키워드
keywords = ['총질소T-N', '총인T-P', '클로로필-a']

# MultiIndex 컬럼에서 4번째 level까지 있으므로,
# 각 컬럼 튜플에서 1번 인덱스(두번째 레벨, 즉 '총질소T-N' 등 항목명) 기준으로 필터링
selected_cols = [col for col in df.columns if any(k in col[1] for k in keywords)]

# 선택한 컬럼으로 새로운 데이터프레임 생성
df_selected = df[selected_cols]

print(df_selected.head())

import pandas as pd

# df : 현재 멀티인덱스 컬럼을 가진 원본 데이터프레임

# 1) 월별 필요한 컬럼(총질소, 총인, 클로로필)만 선택
# 2) 각 월별 데이터를 따로 뽑아서 합침

# 1) '분류' 컬럼(멀티인덱스 4단계 중 첫 4개가 '분류' 관련인 경우가 많으므로, 분류 컬럼 지정)
# 분류 컬럼은 멀티인덱스의 ('No','분류','분류','분류.1') 등으로 구성되어 있을 수 있으므로
# 정확히 어떤 컬럼이 분류인지 확인 후, 예시로 아래와 같이 분류명 컬럼 추출

classification_cols = [col for col in df.columns if '분류' in col[1]]  # 필요시 조정

# 2) 월 리스트
months = [f'2024년 {m}월' for m in range(1,13)]

# 3) 월별 데이터를 담을 리스트
dfs = []

for month in months:
    # 월별 3개 변수 컬럼만 추출 (총질소T-N, 총인T-P, 클로로필-a Chlorophyll-a)
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    # 분류 컬럼과 월별 데이터만 추출
    temp = df[classification_cols + month_cols].copy()

    # 컬럼 이름 단순화 (멀티인덱스 -> 단일 컬럼명)
    # ex: ('2024년 1월', '총질소T-N', 'mg/L', '원자료') -> '총질소T-N'
    temp.columns = [col[1] if '분류' in col[1] else col[1] for col in temp.columns]

    # 월 정보 컬럼 추가
    temp['월'] = month

    dfs.append(temp)

# 4) 월별 데이터 합치기
df_long = pd.concat(dfs, ignore_index=True)

# 5) 컬럼 순서 정리 (분류 컬럼 + 월 + 3개 변수)
cols_order = [col for col in classification_cols]
cols_order = [col[1] for col in classification_cols] + ['월', '총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']

df_long = df_long[cols_order]

print(df_long.head())

# 예를 들어, 중복된 분류 컬럼 9개가 반복되어 있다면,
# 분류 관련 컬럼을 중복 없이 하나만 남기도록 선택

# 1) 분류 컬럼명 리스트 (중복된 것 중 첫 3개만 선택)
classification_cols = [col for col in df.columns if '분류' in col[1]]

# 중복이 있을 수 있으므로, 컬럼명을 기준으로 중복 제거
seen = set()
unique_classification_cols = []
for col in classification_cols:
    if col[1] not in seen:
        unique_classification_cols.append(col)
        seen.add(col[1])

# 2) 위에서 월별 데이터 컬럼과 분류 컬럼 조합 예시
months = [f'2024년 {m}월' for m in range(1, 13)]

dfs = []

for month in months:
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    temp = df[unique_classification_cols + month_cols].copy()

    # 컬럼명 단순화
    temp.columns = [col[1] for col in unique_classification_cols] + [col[1] for col in month_cols]

    temp['월'] = month

    dfs.append(temp)

df_long = pd.concat(dfs, ignore_index=True)

print(df_long.head())

# 1. df_tp 복사본 생성 (원본에 영향 안주게)
df_tp = df_long[['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a', '월']].copy()

# 숫자형 변환 (변환 불가시 NaN 처리)
df_tp['총인T-P'] = pd.to_numeric(df_tp['총인T-P'], errors='coerce')
df_tp['총질소T-N'] = pd.to_numeric(df_tp['총질소T-N'], errors='coerce')
df_tp['클로로필-a Chlorophyll-a'] = pd.to_numeric(df_tp['클로로필-a Chlorophyll-a'], errors='coerce')

#2024금강권역_총인-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tp = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_bound = df_tp['총인T-P'].quantile(0.01)
upper_bound = df_tp['총인T-P'].quantile(0.99)

# 이상치 제거
df_tp_filtered = df_tp[(df_tp['총인T-P'] >= lower_bound) & (df_tp['총인T-P'] <= upper_bound)]

# 시각화 (월별로 나눠서 회귀선 포함)
sns.lmplot(
    data=df_tp_filtered,
    x='총인T-P',
    y='클로로필-a Chlorophyll-a',
    col='월',           # 월별 분할
    col_wrap=4,         # 한 줄에 4개씩 출력
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'blue'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총인(T-P) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2024금강권역_총질소-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tn = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_tn = df_tn['총질소T-N'].quantile(0.01)
upper_tn = df_tn['총질소T-N'].quantile(0.99)

# 이상치 제거
df_tn_filtered = df_tn[(df_tn['총질소T-N'] >= lower_tn) & (df_tn['총질소T-N'] <= upper_tn)]

# 시각화
sns.lmplot(
    data=df_tn_filtered,
    x='총질소T-N',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'red'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총질소(T-N) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2024금강권역_총영양염류-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거 및 총영양염류 계산
df_nut = df_tp.dropna()
df_nut['총영양염류'] = df_nut['총질소T-N'] + df_nut['총인T-P']

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_nut = df_nut['총영양염류'].quantile(0.01)
upper_nut = df_nut['총영양염류'].quantile(0.99)

# 이상치 제거
df_nut_filtered = df_nut[(df_nut['총영양염류'] >= lower_nut) & (df_nut['총영양염류'] <= upper_nut)]

# 시각화
sns.lmplot(
    data=df_nut_filtered,
    x='총영양염류',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'green'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총영양염류 vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

"""## 2025년_하천수의_수질현황_금강권역"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/재정데이터_미니프로젝트_2조/하천수의+수질현황-금강권역_2025년.csv'
, header=[0,1],encoding='cp949')

df.head()

df.columns

# 상위 컬럼명 확인
print(df.columns[:10])
# 데이터 일부 확인
print(df.head())

import pandas as pd

# 예: df는 이미 위와 같은 MultiIndex 컬럼을 가진 데이터프레임
# df = pd.read_excel(..., header=[0,1,2,3])

# 원하는 키워드
keywords = ['총질소T-N', '총인T-P', '클로로필-a']

# MultiIndex 컬럼에서 4번째 level까지 있으므로,
# 각 컬럼 튜플에서 1번 인덱스(두번째 레벨, 즉 '총질소T-N' 등 항목명) 기준으로 필터링
selected_cols = [col for col in df.columns if any(k in col[1] for k in keywords)]

# 선택한 컬럼으로 새로운 데이터프레임 생성
df_selected = df[selected_cols]

print(df_selected.head())

import pandas as pd

# df : 현재 멀티인덱스 컬럼을 가진 원본 데이터프레임

# 1) 월별 필요한 컬럼(총질소, 총인, 클로로필)만 선택
# 2) 각 월별 데이터를 따로 뽑아서 합침

# 1) '분류' 컬럼(멀티인덱스 4단계 중 첫 4개가 '분류' 관련인 경우가 많으므로, 분류 컬럼 지정)
# 분류 컬럼은 멀티인덱스의 ('No','분류','분류','분류.1') 등으로 구성되어 있을 수 있으므로
# 정확히 어떤 컬럼이 분류인지 확인 후, 예시로 아래와 같이 분류명 컬럼 추출

classification_cols = [col for col in df.columns if '분류' in col[1]]  # 필요시 조정

# 2) 월 리스트
months = [f'2025년 {m}월' for m in range(1,13)]

# 3) 월별 데이터를 담을 리스트
dfs = []

for month in months:
    # 월별 3개 변수 컬럼만 추출 (총질소T-N, 총인T-P, 클로로필-a Chlorophyll-a)
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    # 분류 컬럼과 월별 데이터만 추출
    temp = df[classification_cols + month_cols].copy()

    # 컬럼 이름 단순화 (멀티인덱스 -> 단일 컬럼명)
    # ex: ('2024년 1월', '총질소T-N', 'mg/L', '원자료') -> '총질소T-N'
    temp.columns = [col[1] if '분류' in col[1] else col[1] for col in temp.columns]

    # 월 정보 컬럼 추가
    temp['월'] = month

    dfs.append(temp)

# 4) 월별 데이터 합치기
df_long = pd.concat(dfs, ignore_index=True)

# 5) 컬럼 순서 정리 (분류 컬럼 + 월 + 3개 변수)
cols_order = [col for col in classification_cols]
cols_order = [col[1] for col in classification_cols] + ['월', '총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']

df_long = df_long[cols_order]

print(df_long.head())

# 예를 들어, 중복된 분류 컬럼 9개가 반복되어 있다면,
# 분류 관련 컬럼을 중복 없이 하나만 남기도록 선택

# 1) 분류 컬럼명 리스트 (중복된 것 중 첫 3개만 선택)
classification_cols = [col for col in df.columns if '분류' in col[1]]

# 중복이 있을 수 있으므로, 컬럼명을 기준으로 중복 제거
seen = set()
unique_classification_cols = []
for col in classification_cols:
    if col[1] not in seen:
        unique_classification_cols.append(col)
        seen.add(col[1])

# 2) 위에서 월별 데이터 컬럼과 분류 컬럼 조합 예시
months = [f'2025년 {m}월' for m in range(1, 13)]

dfs = []

for month in months:
    month_cols = [col for col in df.columns if col[0] == month and col[1] in ['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a']]

    temp = df[unique_classification_cols + month_cols].copy()

    # 컬럼명 단순화
    temp.columns = [col[1] for col in unique_classification_cols] + [col[1] for col in month_cols]

    temp['월'] = month

    dfs.append(temp)

df_long = pd.concat(dfs, ignore_index=True)

print(df_long.head())

# 1. df_tp 복사본 생성 (원본에 영향 안주게)
df_tp = df_long[['총질소T-N', '총인T-P', '클로로필-a Chlorophyll-a', '월']].copy()

# 숫자형 변환 (변환 불가시 NaN 처리)
df_tp['총인T-P'] = pd.to_numeric(df_tp['총인T-P'], errors='coerce')
df_tp['총질소T-N'] = pd.to_numeric(df_tp['총질소T-N'], errors='coerce')
df_tp['클로로필-a Chlorophyll-a'] = pd.to_numeric(df_tp['클로로필-a Chlorophyll-a'], errors='coerce')

#2025금강권역_총인-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tp = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_bound = df_tp['총인T-P'].quantile(0.01)
upper_bound = df_tp['총인T-P'].quantile(0.99)

# 이상치 제거
df_tp_filtered = df_tp[(df_tp['총인T-P'] >= lower_bound) & (df_tp['총인T-P'] <= upper_bound)]

# 시각화 (월별로 나눠서 회귀선 포함)
sns.lmplot(
    data=df_tp_filtered,
    x='총인T-P',
    y='클로로필-a Chlorophyll-a',
    col='월',           # 월별 분할
    col_wrap=4,         # 한 줄에 4개씩 출력
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'blue'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총인(T-P) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2025금강권역_총질소-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거
df_tn = df_tp.dropna()

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_tn = df_tn['총질소T-N'].quantile(0.01)
upper_tn = df_tn['총질소T-N'].quantile(0.99)

# 이상치 제거
df_tn_filtered = df_tn[(df_tn['총질소T-N'] >= lower_tn) & (df_tn['총질소T-N'] <= upper_tn)]

# 시각화
sns.lmplot(
    data=df_tn_filtered,
    x='총질소T-N',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'red'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총질소(T-N) vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()

#2025금강권역_총영양염류-클로로필 상관관계
import seaborn as sns
import matplotlib.pyplot as plt

# 결측치 제거 및 총영양염류 계산
df_nut = df_tp.dropna()
df_nut['총영양염류'] = df_nut['총질소T-N'] + df_nut['총인T-P']

# 이상치 경계값 설정 (1%, 99% 분위수)
lower_nut = df_nut['총영양염류'].quantile(0.01)
upper_nut = df_nut['총영양염류'].quantile(0.99)

# 이상치 제거
df_nut_filtered = df_nut[(df_nut['총영양염류'] >= lower_nut) & (df_nut['총영양염류'] <= upper_nut)]

# 시각화
sns.lmplot(
    data=df_nut_filtered,
    x='총영양염류',
    y='클로로필-a Chlorophyll-a',
    col='월',
    col_wrap=4,
    height=4,
    aspect=1.2,
    scatter_kws={'alpha': 0.6},
    line_kws={'color': 'green'}
)

plt.subplots_adjust(top=0.9)
plt.suptitle("월별 총영양염류 vs 클로로필-a 관계 (이상치 제거 후)", fontsize=16)
plt.show()